name: Batch GitOps Dispatch

on:
  workflow_call:
    inputs:
      gitops_repository:
        description: "Target repo for repository_dispatch (e.g. your-org/gitops)"
        required: true
        type: string
      gitops_repository_event_type:
        description: "Event type for batch update"
        required: false
        default: "batch-image-update"
        type: string
      apps_json:
        description: "JSON array of app objects with 'app' and 'tag' fields"
        required: true
        type: string
      deployment_type:
        description: "Type of deployment (release, manual, pr)"
        required: false
        default: "manual"
        type: string
    secrets:
      PAT:
        required: true

jobs:
  batch-dispatch:
    name: Send Batch GitOps Update
    runs-on: ubuntu-latest
    steps:
      - name: Send batch repository dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            "https://api.github.com/repos/${{ inputs.gitops_repository }}/dispatches" \
            -d '{
              "event_type": "${{ inputs.gitops_repository_event_type }}",
              "client_payload": {
                "deployment_type": "${{ inputs.deployment_type }}",
                "apps": ${{ toJson(inputs.apps_json) }}
              }
            }'
